---
  # https://swagger.io/docs/specification/2-0/basic-structure/
  swagger: "2.0"
  #openapi: "3.0.0"
  info: 
    title: "Sample API"
    description: "Power your application with APIs"
  consumes:
    - application/json
  produces: 
    - application/json
  securityDefinitions:
    # X-App-Id:
    AppIdHeader:
      type: apiKey
      in: header
      name: X-App-Id
    # X-Access-Token
    AccessTokenHeader:
      type: apiKey
      in: header
      name: X-Access-Token
  security:
    - AppIdHeader: []
      AccessTokenHeader: []
  responses:
    # Generic API response object
    ApiResponse:
      type: object
      descrription: generic API response
      properties:
        status:
          description: status code, 200 usually means 'successful'
          type: integer
        msg:
          description: message further describing API status code
          type: string
        data:
          description: (optional) output returned from API
          type: object
    # API response: successful
    Success:
      description: API call finished successful
      type: object
      properties:
        status:
          type: integer
          enum: [200]
        data:
          description: (optional) output returned from API
          type: object
    # API response: "not found"
    NotFound:
      description: The requested item was not found
      type: object
      properties:
        status:
          type: integer
          enum: [404]
    # API response: "access denied"
    AccessDenied:
      description: Client is not authorized to call the API
      type: object
      properties:
        status:
          type: integer
          enum: [403]
    # API response: "error on client side"
    ErrorClient:
      description: There was error at client side (e.g. invalid parameters)
      type: object
      properties:
        status:
          type: integer
          enum: [400]
    # API response: "error on server side"
    ErrorServer:
      description: There was error at server side (e.g. exception)
      type: object
      properties:
        status:
          type: integer
          enum: [500]
    # API response: "not implemented"
    NotImplemented:
      description: This API/function has not been implemented yet.
      type: object
      properties:
        status:
          type: integer
          enum: [501]
